
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author olalindsten
 */
public class connection extends javax.swing.JFrame {

    /**
     * Creates new form connection
     */
    public connection() {
        initComponents();
        show_filmer();
    }
    
    public Connection getConnection(){
        Connection conn;
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/filmregister", "root", "");
            return conn;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
    
    public ArrayList<Film> getFilmerList(){
        
        ArrayList<Film> filmerList = new ArrayList<Film>();
        Connection connection = getConnection();
        
        String query = "SELECT * FROM `filmer`";
        Statement st;
        ResultSet rs;
        
        try {
            st = connection.createStatement();
            rs = st.executeQuery(query);
            Film film;
            while(rs.next()){
                film = new Film(rs.getString("titel"),
                        rs.getString("genre"),rs.getString("regissör"),rs.getString("betyg"),rs.getString("längd"));
                filmerList.add(film);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        return filmerList;       
    } 
    
    //display data in Jtable
    
    public void show_filmer(){
        
        ArrayList<Film> list = getFilmerList();
        DefaultTableModel model = (DefaultTableModel)p1.getModel();
        Object[] row = new Object [5];
        for (int i = 0; i < list.size(); i++) {
           
            row[1] = list.get(i).gettitel();
            row[2] = list.get(i).getgenre();
            row[3] = list.get(i).getregissör();
            row[4] = list.get(i).getbetyg();
            row[5] = list.get(i).getlängd();
            
            model.addRow(row);
        }
    }
    
    //excute query
    public void executeSQLQuery(String query,String message){
        Connection conn = getConnection();
        Statement st;
        
        try {
            st=conn.createStatement();
            if((st.executeUpdate(query)) == 1){
                
                JOptionPane.showMessageDialog(null, "Data " + message+ " Succesfully");
            }else{
                
                JOptionPane.showMessageDialog(null, "Data not" + message);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        p1 = new javax.swing.JTable();
        btnfilm = new javax.swing.JButton();
        text_titel = new javax.swing.JTextField();
        Jtitel = new javax.swing.JLabel();
        jgenre = new javax.swing.JLabel();
        jregissor = new javax.swing.JLabel();
        jbetyg = new javax.swing.JLabel();
        jlangd = new javax.swing.JLabel();
        text_regissor = new javax.swing.JTextField();
        text_genre = new javax.swing.JTextField();
        text_langd = new javax.swing.JTextField();
        text_betyg = new javax.swing.JTextField();
        spara = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Olas filmdatabas");

        p1.setAutoCreateRowSorter(true);
        p1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Genre", "Regissör", "Betyg", "Längd"
            }
        ));
        p1.setGridColor(new java.awt.Color(0, 0, 0));
        p1.setSelectionBackground(new java.awt.Color(0, 0, 0));
        p1.getTableHeader().setReorderingAllowed(false);
        p1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(p1);

        btnfilm.setText("Visa filmer");
        btnfilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfilmActionPerformed(evt);
            }
        });

        text_titel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_titelActionPerformed(evt);
            }
        });

        Jtitel.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        Jtitel.setForeground(new java.awt.Color(240, 240, 240));
        Jtitel.setText("Title");

        jgenre.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        jgenre.setForeground(new java.awt.Color(240, 240, 240));
        jgenre.setText("Genre");

        jregissor.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        jregissor.setForeground(new java.awt.Color(240, 240, 240));
        jregissor.setText("Regissör");

        jbetyg.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        jbetyg.setForeground(new java.awt.Color(240, 240, 240));
        jbetyg.setText("Betyg");

        jlangd.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        jlangd.setForeground(new java.awt.Color(240, 240, 240));
        jlangd.setText("Längd");

        text_genre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_genreActionPerformed(evt);
            }
        });

        spara.setText("Spara");
        spara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sparaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jtitel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_titel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jgenre, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(text_genre, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jregissor, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(jbetyg, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(text_regissor, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(text_betyg, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlangd, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(text_langd, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 53, Short.MAX_VALUE)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnfilm, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(spara, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnfilm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jtitel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jgenre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jregissor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbetyg, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlangd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_titel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_genre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_regissor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_betyg, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_langd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(spara, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnfilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfilmActionPerformed

        
        DefaultTableModel model = (DefaultTableModel) p1.getModel();
        try {
            
            model.setRowCount(0);
            
            Connection conn = getConnection();
            Statement stmt = conn.createStatement();
            String query = "Select * from filmer;";
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next()) {
                String Title = rs.getString("titel");
                String Genre = rs.getString("genre");
                String Regissör = rs.getString("regissör");
                String Betyg = rs.getString("betyg");
                String Langd = rs.getString("längd");

                model.addRow(new Object[]{Title, Genre, Regissör, Betyg, Langd});

            }

            rs.close();
            stmt.close();
            conn.close();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, e);
        }


    }//GEN-LAST:event_btnfilmActionPerformed

    
    
    private void text_titelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_titelActionPerformed


    }//GEN-LAST:event_text_titelActionPerformed

    private void text_genreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_genreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_genreActionPerformed

    private void sparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sparaActionPerformed

        String query = "INSERT INTO `filmer`(`titel`, `genre`, `regissör`, `betyg`, `längd`) "
                + "VALUES ('"+text_titel.getText()+"','"+text_genre.getText()+"','"+text_regissor.getText()+"',"
                + "'"+text_betyg.getText()+"','"+text_langd.getText()+"')";
        
        executeSQLQuery(query,"Inserted");
        
        
       
                /*
        try {
            
            
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/filmregister", "root", "");
            DefaultTableModel model = (DefaultTableModel) p1.getModel();
            Statement stmt = conn.createStatement();
            ResultSet rs;
            PreparedStatement pst;


            
            String sql = "SELECT ID,titel,genre,regissör,betyg,längd FROM filmer WHERE ID =?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, text_titel.getText());

            rs = pst.executeQuery();
            if (rs.next()) {
                String titel = rs.getString("titel");
                text_titel.setText(titel);
                String genre = rs.getString("genre");
                text_genre.setText(genre);
                String regi = rs.getString("regissör");
                text_regissor.setText(regi);
                String betyg = rs.getString("betyg");
                text_betyg.setText(betyg);
                String langd = rs.getString("längd");
                text_langd.setText(langd);

            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);

        } */  
    }//GEN-LAST:event_sparaActionPerformed

    private void p1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1MouseClicked
        
        int i = p1.getSelectedRow();
        TableModel model = p1.getModel();
        text_titel.setText(model.getValueAt(i, 0).toString());
        text_genre.setText(model.getValueAt(i, 1).toString());
        text_regissor.setText(model.getValueAt(i, 2).toString());
        text_betyg.setText(model.getValueAt(i, 3).toString());
        text_langd.setText(model.getValueAt(i, 4).toString());
        
    }//GEN-LAST:event_p1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(connection.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(connection.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(connection.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(connection.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new connection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jtitel;
    private javax.swing.JButton btnfilm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jbetyg;
    private javax.swing.JLabel jgenre;
    private javax.swing.JLabel jlangd;
    private javax.swing.JLabel jregissor;
    private javax.swing.JTable p1;
    private javax.swing.JButton spara;
    private javax.swing.JTextField text_betyg;
    private javax.swing.JTextField text_genre;
    private javax.swing.JTextField text_langd;
    private javax.swing.JTextField text_regissor;
    private javax.swing.JTextField text_titel;
    // End of variables declaration//GEN-END:variables
}
